name: Rust

on:
  push:
    branches: [ "rewrite" ]
  pull_request:
    branches: [ "rewrite" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install latest nightly with rustfmt
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Check format
        run: cargo fmt --all -- --check

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install latest nightly Rust toolchain with clippy
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: clippy

    - name: Setup cache
      uses: Swatinem/rust-cache@v1

    - name: Build
      run: cargo build --verbose

    - name: Run clippy
      run: cargo clippy --workspace -- -D clippy::all -D clippy::pedantic -D clippy::nursery -D clippy::cargo